name: Build Linux x86_64 Binary
run-name: Build Linux x86_64
# on: [push]
on:
  push:
    branches:
      - main
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Info printout
        run: |
          echo "The job was automatically triggered by a ${{ github.event_name }} event."
          echo "This job is now running on a ${{ runner.os }} server hosted by GitHub!"
          echo "The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Import flutter action package
        uses: subosito/flutter-action@v2.12.0
        with:
          channel: 'stable'
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Initial cleaning
        run: flutter clean && flutter pub get
      - name: Rebuild icons
        run: flutter pub run flutter_launcher_icons 
      - name: Configure Linux desktop environment
        run: flutter create --platforms=linux .
      - name: Install Linux build dependencies
        run: |
          sudo apt-get update -y
          sudo apt-get install -y ninja-build libgtk-3-dev
          sudo apt-get install -y libunwind-dev
          sudo apt-get install -y libgstreamer1.0-dev libgstreamer-plugins-base1.0-dev libgstreamer-plugins-bad1.0-dev gstreamer1.0-plugins-base gstreamer1.0-plugins-good gstreamer1.0-plugins-bad gstreamer1.0-plugins-ugly gstreamer1.0-libav gstreamer1.0-tools gstreamer1.0-x gstreamer1.0-alsa gstreamer1.0-gl gstreamer1.0-gtk3 gstreamer1.0-qt5 gstreamer1.0-pulseaudio
      - name: flutter doctor output
        run: flutter doctor
      - name: Build Linux version
        run: flutter build linux
